<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Beatok.Application\Beatok.Application.csproj" />
      <ProjectReference Include="..\Beatok.Domain\Beatok.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Core" Version="4.0.100.3" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.100.3" />
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
      <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    </ItemGroup>

</Project>
